name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v3
      ACR_NAME: akscon1
      ACR_LOGIN_SERVER: akscon1.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login using OIDC
        uses: Azure/login@v2.3.0
        with:          
          client-id: e1438469-06c5-448d-88c2-29ab744032c2
          tenant-id: 3d084a01-eb62-47fe-bb1e-748c68591432
          subscription-id: cfc0d37c-0341-4d06-bcf3-35b93770a2ee

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME
      

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
